djangoTest/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import DEBUG, MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('performance_review.urls', namespace='application')),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

performance_review/urls.py
from django.urls import path
from .views import *

app_name = 'application'
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('help/', help_view, name='help'),
    path('accounts/login/', view_login, name='login'),
    path('accounts/logout/', view_logout, name='logout'),

    path('employees/', employees, name='employees'),
    path('employee/<int:pk>/', employee, name='employee'),
    path('add/employee/', add_employee, name='add_employee'),
    path('update/employee/<int:pk>/', update_employee, name='update_employee'),
    path('delete/employee/<int:pk>/', delete_employee, name='delete_employee'),

    path('reviews/', reviews, name='reviews'),
    path('review/<int:pk>/', review, name='review'),
    path('add/review/', add_review, name='add_review'),
    path('update/review/<int:pk>/', update_review, name='update_review'),
    path('delete/review/<int:pk>/', delete_review, name='delete_review'),

    path('emp_reviews', emp_reviews, name='emp_reviews'),
]

performance_review/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver


# from ckeditor.fields import RichTextField


class Employee(models.Model):
    EMP_GENDER = (
        ('m', 'Male'),
        ('f', 'Female')
    )
    EMP_RANKS = (
        ('CEO', 'Chief Executive Officer'),
        ('DIR', 'Director'),
        ('MAN', 'Manager'),
        ('WOR', 'Worker'),
        ('OTH', 'Other'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='emp/profiles/', null=True, blank=True)
    gender = models.CharField(max_length=1, default='m', null=False, blank=False, choices=EMP_GENDER)
    contact_no = models.CharField(
        max_length=18, null=True, blank=True, help_text='employee phone or landline number'
    )
    address = models.TextField(
        null=True, blank=True, help_text='Complete address within area/street, city state and country etc.'
    )
    nic = models.CharField(max_length=50, null=True, blank=True, help_text='National Identification Card or ID card')
    org_id = models.CharField(max_length=50, null=True, blank=True,
                              help_text='Organizational Registration Number or ID')
    rank = models.CharField(
        max_length=3, null=True, blank=True, choices=EMP_RANKS,
        help_text='Employee Rank/Post/Destination within organization'
    )
    date_of_birth = models.DateTimeField(null=True, blank=True, help_text='Date of Birth - Format must be YYYY-MM-DD')
    joined_on = models.DateTimeField(null=True, blank=True, help_text='Date of Joining - Format must be YYYY-MM-DD')
    updated_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Employees'

    def __str__(self):
        return f"{self.pk} {self.user.first_name} {self.user.last_name}"


class Review(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    description = models.TextField(
        max_length=1000, null=False, blank=False, help_text='small description of this task 25-100 characters'
    )
    is_active = models.BooleanField(
        null=False, blank=False, default=True,
        help_text='If you check this it means the task is active and if you disable it it will be removed temporary'
    )
    created_on = models.DateTimeField(auto_now=True)
    updated_on = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     verbose_name_plural = 'Reviews'

    def __str__(self):
        return f"{self.pk} {self.employee} "

    def save(self, *args, **kwargs):
        self.slug = slugify(self.employee)
        super(Review, self).save(*args, **kwargs)

templates/application/add_employee.html
{% extends 'application/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block base_title %}
    Add Employee
{% endblock %}

{% block base_page_heading %}
    Add Employee
{% endblock %}

{% block base_content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-7">
                <div class="card">
                    <div class="card-body p-4">

                        {% if form.instance.profile_image%}
                            <div class="text-center">
                                <img src="{{ form.instance.profile_image.url }}"
                                     class="rounded-circle img-fluid img-responsive" height="200" width="200">
                            </div>
                            <hr>
                        {% endif %}

                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-success"><i class="fa fa-check"></i> Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/application/add_task.html
{% extends 'application/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block base_page_css_links %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
{% endblock %}


{% block base_title %}
    Add/Update-Review
{% endblock %}

{% block base_page_heading %}
    Add/Update Review <br>
    <a href="{% url 'application:add_review' %}" class="btn btn-success btn-sm mt-1"><i class="fa fa-plus-circle"></i> Add New</a>
{% endblock %}

{% block base_content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-10">
                <div class="card">

                    <div class="card-body p-4">

                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.media }}
                            {{ form|crispy }}
                            <button class="btn btn-success"><i class="fa fa-check"></i> Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block base_page_javascript_links %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
            integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
{% endblock %}

{% block base_page_javascript_code %}
    <script>
        $(document).ready(function () {
            $('#id_start_time').datetimepicker({
                format: 'Y-m-d H:i:s',
            });

            $('#id_end_time').datetimepicker({
                format: 'Y-m-d H:i:s',
            });
        });
    </script>
{% endblock %}

templates/application/base.html
{% load static %}
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>
        EMS |
        {% block base_title %}
            Home
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="EMP Admin Panel" name="description">
    <meta content="mark" name="author">

    <link rel="shortcut icon" href="{% static 'application/images/favicon.ico' %}">

    {% block base_theme %}
        <link href="{% static 'application/css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet">
        <link href="{% static 'application/css/app.min.css' %}" id="app-style" rel="stylesheet">
    {% endblock %}

    <link href="{% static 'application/css/icons.min.css' %}" rel="stylesheet">
    {% block base_page_css_links %}

    {% endblock %}
</head>

<body data-topbar="dark" data-layout="horizontal">

{% block base_no_content %}
    <div id="layout-wrapper">

        {% block base_header %}
            {% include 'application/include/header.html' %}
        {% endblock %}

        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="container-fluid">

                    <div class="row">
                        {% include 'application/message.html' %}
                    </div>

                    <!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box d-flex align-items-center justify-content-between">

                                <h4 class="mb-0 font-size-18">
                                    {% block base_page_heading %} {% endblock %}
                                </h4>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">

                            {% block base_content %}{% endblock %}

                        </div>
                    </div>

                </div> <!-- container-fluid -->
            </div>

        </div>
        <!-- end main content-->

    </div>
{% endblock %}


{% block base_theme_activation %}

{% endblock %}


<!-- JAVASCRIPT -->
<script src="{% static 'application/libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'application/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'application/libs/metismenu/metisMenu.min.js' %}"></script>
<script src="{% static 'application/libs/simplebar/simplebar.min.js' %}"></script>
<script src="{% static 'application/libs/node-waves/waves.min.js' %}"></script>

{% block base_page_javascript_links %}{% endblock %}

<script src="{% static 'application/js/app.js' %}"></script>
</body>
</html>

{% block base_page_javascript_code %}{% endblock %}

templates/application/employee_dashboard.html
{% extends 'application/base.html' %}
{% load static %}

{% block seller_base_title %}
    Dashboard
{% endblock %}

{% block base_page_css_links %}
    <link rel="stylesheet" href="{% static 'application/libs/owl.carousel/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'application/libs/owl.carousel/assets/owl.theme.default.min.css' %}">
{% endblock %}

{% block base_content %}


    {# FISRT LINE #}
    <p class="card-title">Hi, {{ request.user }}</p>
    <div class="row">


             <div class="col-xl-12">

                <div class="col-sm-3">
                    <div class="card">

                        <div class="card-body">
                            <div class="text-muted text-center">
                                <h2 class="mb-4"><i
                                        class="fa fa-calendar-alt p-3 bg-soft-primary rounded-circle text-primary"></i>
                                </h2>
                                <a class="btn btn-sm btn-success" href="{% url 'application:add_review' %}">  <h5 class="font-size-14 mb-1">ADD Review</h5></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-muted text-center">
                                <h2 class="mb-4"><i
                                        class="fa fa-calendar-check p-3 bg-soft-success rounded-circle text-success"></i>
                                </h2>
                                 <a class="btn btn-sm btn-success" href="{% url 'application:emp_reviews' %}">  <h5 class="font-size-14 mb-1">My Reviews</h5></a>
                            </div>
                        </div>
                    </div>
                </div>
{##}
{#                <div class="col-sm-3">#}
{#                    <div class="card">#}
{#                        <div class="card-body">#}
{#                            <div class="text-muted text-center">#}
{#                                <h2 class="mb-4"><i#}
{#                                        class="fa fa-calendar-times p-3 bg-soft-danger rounded-circle text-danger"></i>#}
{#                                </h2>#}
{#                                <h5 class="font-size-14 mb-1">Failed Tasks</h5>#}
{#                                <h4>2</h4>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{##}
{#                <div class="col-sm-3">#}
{#                    <div class="card">#}
{#                        <div class="card-body">#}
{#                            <div class="text-muted text-center">#}
{#                                <h2 class="mb-4"><i#}
{#                                        class="fa fa-star p-3 bg-soft-warning rounded-circle text-warning"></i></h2>#}
{#                                <h5 class="font-size-14 mb-1">Rating</h5>#}
{#                                <h4>9.8 - 10</h4>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}


            </div>
            <!-- end row -->
        </div>
{#    </div>#}
    <br>

{#    <p class="card-title">Current Running Tasks</p>#}
{#    <div class="row">#}
{#        <div class="col-12">#}
{#            <div class="card">#}
{#                <div class="card-body">#}
{#                    <h4 class="card-title">TASK: Packing Candies</h4>#}
{#                    <p class="card-title-desc mb-5">#}
{#                        10 employees have been assigned to this task _ task start time 10:00 upto 01:00 pm#}
{#                    </p>#}
{#                    <div class="">#}
{##}
{#                        <div class="progress mb-4" style="height: 40px;">#}
{#                            <div class="progress-bar bg-success progress-bar-striped progress-bar-animated py-4 text-right"#}
{#                                 role="progressbar" style="width: 90%;" aria-valuenow="90"#}
{#                                 aria-valuemin="0" aria-valuemax="100">#}
{#                                <p class="h3 p-2 text-white">Flint <i class="fa fa-running bx-tada"></i></p>#}
{#                            </div>#}
{#                        </div>#}
{##}
{#                        <div class="progress mb-4" style="height: 40px;">#}
{#                            <div class="progress-bar bg-primary progress-bar-striped progress-bar-animated py-4 text-right"#}
{#                                 role="progressbar" style="width: 80%;" aria-valuenow="80"#}
{#                                 aria-valuemin="0" aria-valuemax="100">#}
{#                                <p class="h3 p-2 text-white">Mark <i class="fa fa-running bx-tada"></i></p>#}
{#                            </div>#}
{#                        </div>#}
{##}
{#                        <div class="progress mb-4" style="height: 40px;">#}
{#                            <div class="progress-bar bg-info progress-bar-striped progress-bar-animated py-4 text-right"#}
{#                                 role="progressbar" style="width: 60%;" aria-valuenow="60"#}
{#                                 aria-valuemin="0" aria-valuemax="100">#}
{#                                <p class="h3 p-2 text-white">Jane <i class="fa fa-running bx-tada"></i></p>#}
{#                            </div>#}
{#                        </div>#}
{##}
{#                        <div class="progress mb-4" style="height: 40px;">#}
{#                            <div class="progress-bar bg-warning progress-bar-striped progress-bar-animated py-4 text-right"#}
{#                                 role="progressbar" style="width: 50%;" aria-valuenow="50"#}
{#                                 aria-valuemin="0" aria-valuemax="100">#}
{#                                <p class="h3 p-2 text-white">Stephen<i class="fa fa-running bx-tada"></i></p>#}
{#                            </div>#}
{#                        </div>#}
{##}
{#                        <div class="progress mb-4" style="height: 40px;">#}
{#                            <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated py-4 text-right"#}
{#                                 role="progressbar" style="width: 30%;" aria-valuenow="30"#}
{#                                 aria-valuemin="0" aria-valuemax="100">#}
{#                                <p class="h3 p-2 text-white">Waseem <i class="fa fa-running bx-tada"></i></p>#}
{#                            </div>#}
{#                        </div>#}
{##}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}

{% endblock %}

{% block base_page_javascript_links %}

    <script src="{% static 'application/libs/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'application/js/pages/ico-landing.init.js' %}"></script>
    <script src="{% static 'application/libs/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'application/js/pages/apexcharts.init.js' %}"></script>
{% endblock %}

templates/application/employees.html
{% extends 'application/base.html' %}
{% load static %}
{% block base_title %}Employees{% endblock %}

{% block base_page_css_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block base_page_heading %}Your Employees{% endblock %}


{% block base_content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="text-right mb-4">
                        <a class="btn btn-sm btn-success" href="{% url 'application:add_employee' %}"><i class="fa fa-user-plus"></i> Add Employee</a>
                    </div>
                    <div class="table-responsive mb-0">
                        <table id="employees" class="table table-striped">
                            <thead class="">
                            <tr>
                                <th data-priority="1">ID</th>
                                <th data-priority="3">Name</th>
                                <th data-priority="3">Phone</th>
                                <th data-priority="6">Email</th>
                                <th data-priority="6">Role</th>
                                <th data-priority="6">Joined</th>
                                <th data-priority="3">Status</th>
                                <th data-priority="3">Action</th>
                            </tr>
                            </thead>
                            <tbody class="small">
                            {% if employees %}
                                {% for emp in employees %}

                                    <tr>
                                        <th>{{ emp.user.pk }}</th>
                                        <td>{{ emp.user.first_name }} {{ emp.user.last_name }}</td>
                                        <td>{{ emp.contact_no }}</td>
                                        <td>{{ emp.user.email }}</td>
                                        <td>{{ emp.get_rank_display }}</td>
                                        <td>{{ emp.joined_on }}</td>
                                        <td>
                                            {% if emp.user.is_active %}
                                                <i class="fa fa-check text-success"></i>
                                            {% else %}
                                                <i class="fa fa-times text-danger"></i>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a href="{% url 'application:update_employee' emp.pk %}"><i
                                                    class="fa fa-edit text-primary"></i></a>
                                            <a href="{% url 'application:employee' emp.pk %}"><i
                                                    class="fa fa-chart-bar text-primary"></i></a>
                                            <a href="{% url 'application:delete_employee' emp.pk %}"><i
                                                    class="fa fa-trash text-danger"></i></a>
                                        </td>
                                    </tr>

                                {% endfor %}
                            {% endif %}
                            <!-- Repeat -->
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div> <!-- end col -->
    </div>
{% endblock %}

{% block base_page_javascript_links %}

    {# TODO: Security Leak here try to fix this issue later #}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>
{% endblock %}

{% block base_page_javascript_code %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });
    </script>
{% endblock %}

templates/application/tasks.html
{% extends 'application/base.html' %}
{% load static %}
{% block base_title %}Review List{% endblock %}

{% block base_page_css_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block base_page_heading %}Review List{% endblock %}


{% block base_content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="text-right mb-4">
                        <a class="btn btn-sm btn-success" href="{% url 'application:add_review' %}"><i
                                class="fa fa-calendar-plus"></i> Add Review</a>
                    </div>
                    <div class="table-responsive mb-0">
                        <table id="employees" class="table table-striped">
                            <thead class="">
                            <tr>
                                <th data-priority="1">ID</th>
                                <th data-priority="1">Employee</th>
{#                                <th data-priority="3">Start Time</th>#}
{#                                <th data-priority="3">End Time</th>#}
                                <th data-priority="6">Active</th>
                                <th data-priority="6">Created on</th>
                                <th data-priority="6">Last updated</th>
                                <th data-priority="6">Action</th>
                            </tr>
                            </thead>
                            <tbody class="small">
                            {% if tasks %}
                                {% for task in tasks %}

                                    <tr>
                                        <th>{{ task.pk }}</th>
                                        <td>{{ task.employee }}</td>
{#                                        <td>{{ task.start_time }}</td>#}
{#                                        <td>{{ task.end_time }}</td>#}
                                        <td>
                                            {% if task.is_active %}
                                                <i class="fa fa-check text-success"></i>
                                            {% else %}
                                                <i class="fa fa-times text-danger"></i>
                                            {% endif %}
                                        </td>
                                        <td>{{ task.created_on }}</td>
                                        <td>{{ task.updated_on }}</td>
                                        <td>
                                            <a href="{% url 'application:update_review' task.pk %}"><i
                                                    class="fa fa-edit text-primary"></i></a>
                                            <a href="{% url 'application:review' task.pk %}"><i
                                                    class="fa fa-chart-bar text-primary"></i></a>
                                            <a href="{% url 'application:delete_review' task.pk %}"><i
                                                    class="fa fa-trash text-danger"></i></a>
                                        </td>
                                    </tr>

                                {% endfor %}
                            {% endif %}
                            <!-- Repeat -->
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div> <!-- end col -->
    </div>
{% endblock %}

{% block base_page_javascript_links %}

    {# TODO: Security Leak here try to fix this issue later #}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>

{% endblock %}

{% block base_page_javascript_code %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });
    </script>
{% endblock %}