djangoTest/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import DEBUG, MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('performance_review.urls', namespace='application')),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

performance_review/urls.py
from django.urls import path
from .views import *

app_name = 'application'
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('help/', help_view, name='help'),
    path('accounts/login/', view_login, name='login'),
    path('accounts/logout/', view_logout, name='logout'),

    path('employees/', employees, name='employees'),
    path('employee/<int:pk>/', employee, name='employee'),
    path('add/employee/', add_employee, name='add_employee'),
    path('update/employee/<int:pk>/', update_employee, name='update_employee'),
    path('delete/employee/<int:pk>/', delete_employee, name='delete_employee'),

    path('reviews/', reviews, name='reviews'),
    path('review/<int:pk>/', review, name='review'),
    path('add/review/', add_review, name='add_review'),
    path('update/review/<int:pk>/', update_review, name='update_review'),
    path('delete/review/<int:pk>/', delete_review, name='delete_review'),

    path('emp_reviews', emp_reviews, name='emp_reviews'),
]

templates/application/include/header.html
{% load static %}

{# MAIN_HEADER #}
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">

            {# LOGO #}
            <div class="navbar-brand-box">
                <a href="" class="logo logo-dark">
                                <span class="logo-sm">
{#                                    <b class="text-dark">Orgnization <small>Franchise</small></b>#}
                                    <img src="{% static 'application/images/logo-dark.png' %}" alt="" height="22">
                                </span>
                    <span class="logo-lg">
{#                        <b class="text-dark">Orgnization <small>Franchise</small></b>#}
                                    <img src="{% static 'application/images/logo-dark.png' %}" alt="" height="17">
                                </span>
                </a>

                <a href="" class="logo logo-light">
                                <span class="logo-sm">
{#                                    <b class="text-white">Orgnization <small>Franchise</small></b>#}
                                    <img src="{% static 'application/images/logo-light.png' %}" alt="" height="22">
                                </span>
                    <span class="logo-lg">
{#                        <b class="text-white">Orgnization <small>Franchise</small></b>#}
                                    <img src="{% static 'application/images/logo-light.png' %}" alt="" height="19">

                    </span>
                </a>
            </div>

            {# LOGO > BUTTON > SMALL_SCREEN #}
            <button type="button"
                    class="btn btn-sm px-3 font-size-16 d-lg-none header-item waves-effect waves-light"
                    data-toggle="collapse" data-target="#topnav-menu-content">
                <i class="fa fa-fw fa-bars"></i>
            </button>

        </div>

        <div class="d-flex">

            {# FLAGS #}
            <div class="dropdown d-none d-lg-inline-block ml-1">
                <button type="button" class="btn header-item waves-effect" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    <img class="" src="{% static 'application/images/flags/us.jpg' %}" alt="Header Language"
                         height="16">
                </button>
                <div class="dropdown-menu dropdown-menu-right">

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="{% static 'application/images/flags/spain.jpg' %}" alt="user-image" class="mr-1"
                             height="12">
                        <span
                                class="align-middle">Spanish</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="{% static 'application/images/flags/germany.jpg' %}" alt="user-image" class="mr-1"
                             height="12">
                        <span
                                class="align-middle">German</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="{% static 'application/images/flags/italy.jpg' %}" alt="user-image" class="mr-1"
                             height="12">
                        <span
                                class="align-middle">Italian</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="{% static 'application/images/flags/russia.jpg' %}" alt="user-image" class="mr-1"
                             height="12">
                        <span
                                class="align-middle">Russian</span>
                    </a>
                </div>
            </div>

            {# FULL-SCREEN #}
            <div class="dropdown d-none d-lg-inline-block ml-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="bx bx-fullscreen"></i>
                </button>
            </div>

            {# NOTIFICATIONS #}
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect"
                        id="page-header-notifications-dropdown" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                    <i class="bx bx-bell bx-tada"></i>
                    <span class="badge badge-danger badge-pill">1</span>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                     aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0"> Notifications </h6>
                            </div>
                            <div class="col-auto">
                                <a href="#" class="small"> View All</a>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar="init" style="max-height: 230px;">
                        <div class="simplebar-wrapper" style="margin: 0px;">
                            <div class="simplebar-height-auto-observer-wrapper">
                                <div class="simplebar-height-auto-observer"></div>
                            </div>
                            <div class="simplebar-mask">
                                <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                                    <div class="simplebar-content-wrapper"
                                         style="height: auto; overflow: hidden;">
                                        <div class="simplebar-content" style="padding: 0px;">
                                            <a href="" class="text-reset notification-item">
                                                <div class="media">
                                                    <div class="avatar-xs mr-3">
                                                <span class="avatar-title bg-danger rounded-circle font-size-16">
                                                    <i class="bx bx-bar-chart"></i>
                                                </span>
                                                    </div>
                                                    <div class="media-body">
                                                        <h6 class="mt-0 mb-1">Notifitcaions Not Available </h6>
                                                        <div class="font-size-12 text-muted">
                                                            <p class="mb-1">
                                                                Please provide document to developer for notifications
                                                                system.
                                                            </p>
                                                            <p class="mb-0"><i
                                                                    class="mdi mdi-clock-outline"></i> 0
                                                                min ago</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="simplebar-placeholder" style="width: 0px; height: 0px;"></div>
                        </div>
                        <div class="simplebar-track simplebar-horizontal" style="visibility: hidden;">
                            <div class="simplebar-scrollbar"
                                 style="transform: translate3d(0px, 0px, 0px); display: none;"></div>
                        </div>
                        <div class="simplebar-track simplebar-vertical" style="visibility: hidden;">
                            <div class="simplebar-scrollbar"
                                 style="transform: translate3d(0px, 0px, 0px); display: none;"></div>
                        </div>
                    </div>
                    <div class="p-2 border-top">
                        <a class="btn btn-sm btn-link font-size-14 btn-block text-center"
                           href="javascript:void(0)">
                            <i class="mdi mdi-arrow-right-circle mr-1"></i> View More..
                        </a>
                    </div>
                </div>
            </div>

            {# USER #}
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user"
                         src="{% static 'application/images/users/avatar-7.jpg' %}"
                         alt="Header Avatar">
                    <span class="d-none d-xl-inline-block ml-1">{{ request.user }}</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <!-- item-->
                    {% if request.user.is_superuser %}
                        <a class="dropdown-item" href="/admin/auth/user/{{ request.user.pk }}/change/"><i
                                class="bx bx-user font-size-16 align-middle mr-1"></i>
                            Profile</a>
                        <a class="dropdown-item" href="/admin/password_change/">
                            <i class="bx bx-lock font-size-16 align-middle mr-1"></i> Password Change
                        </a>
                        <div class="dropdown-divider"></div>
                    {% else %}

                    {% endif %}

                    <a class="dropdown-item text-danger" href="{% url 'application:logout' %}"><i
                            class="bx bx-power-off font-size-16 align-middle mr-1 text-danger"></i> Logout</a>
                </div>
            </div>

            {#            <div class="dropdown d-inline-block">#}
            {#                <button type="button" class="btn header-item noti-icon right-bar-toggle waves-effect">#}
            {#                    <i class="bx bx-cog bx-spin"></i>#}
            {#                </button>#}
            {#            </div>#}

        </div>
    </div>
</header>

{# SECOND_HEADER #}
{% if request.user.is_superuser %}
    {% include 'application/include/sub_header.html' %}
{% endif %}

templates/application/include/sub_header.html
<div class="topnav">
    <div class="container-fluid">
        <nav class="navbar navbar-light navbar-expand-lg topnav-menu">

            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">

                    {# DASHBOARD #}
                    <li class="nav-item">
                        <a class="nav-link arrow-none" href="{% url 'application:dashboard' %}">
                            <i class="bx bx-home-circle mr-2"></i>Dashboard
                        </a>
                    </li>
                    {# --------------------------------------------------------------------------------------------- #}

                    {# FEATURES #}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-pages" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="bx bx-user mr-2"></i>Manage
                            <div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="topnav-pages">

                            {# EMPLOYEES #}
                            <div class="dropdown">
                                <a class="dropdown-item dropdown-toggle arrow-none" href="#" id="topnav-email"
                                   role="button" data-toggle="dropdown" aria-haspopup="true"
                                   aria-expanded="false">
                                    Employees
                                    <div class="arrow-down"></div>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="topnav-email">
                                    <a href="{% url 'application:employees' %}" class="dropdown-item">View All</a>
                                    <a href="{% url 'application:add_employee' %}" class="dropdown-item">Add New</a>
                                </div>
                            </div>

{#                             Review#}
                            <div class="dropdown">
                                <a class="dropdown-item dropdown-toggle arrow-none" href="#" id="topnav-email"
                                   role="button" data-toggle="dropdown" aria-haspopup="true"
                                   aria-expanded="false">
                                    Reviews
                                    <div class="arrow-down"></div>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="topnav-email">
                                    <a href="{% url 'application:reviews' %}" class="dropdown-item">View All</a>
                                    <a href="{% url 'application:add_review' %}" class="dropdown-item">Add New</a>
                                </div>
                            </div>

                            {# TASKS #}
{#                            <div class="dropdown">#}
{#                                <a class="dropdown-item dropdown-toggle arrow-none" href="#" id="topnav-email"#}
{#                                   role="button" data-toggle="dropdown" aria-haspopup="true"#}
{#                                   aria-expanded="false">#}
{#                                    Daily Progress#}
{#                                    <div class="arrow-down"></div>#}
{#                                </a>#}
{#                                <div class="dropdown-menu" aria-labelledby="topnav-email">#}
{#                                    <a href="{% url 'application:daily_progress_list' %}" class="dropdown-item">List Progress Reports</a>#}
{#                                </div>#}
{#                            </div>#}

                        </div>
                    </li>
                    {# --------------------------------------------------------------------------------------------- #}

{#                     REPORTS#}
{#                    <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-pages" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                            <i class="bx bxs-report mr-2"></i>Reports#}
{#                            <div class="arrow-down"></div>#}
{#                        </a>#}
{#                        <div class="dropdown-menu" aria-labelledby="topnav-pages">#}
{##}
{#                            <a href="{% url 'application:report' %}" class="dropdown-item">Daily</a>#}
{#                        </div>#}
{#                    </li>#}
                    {# --------------------------------------------------------------------------------------------- #}

                    {# SECURITY #}
{#                    <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-pages" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                            <i class="bx bx-lock mr-2"></i>Setting and Security#}
{#                            <div class="arrow-down"></div>#}
{#                        </a>#}
{#                        <div class="dropdown-menu" aria-labelledby="topnav-pages">#}
{##}
{#                            <a href="/admin/" class="dropdown-item">Visit Developers Panel</a>#}
{#                            <a href="/admin/auth/user/" class="dropdown-item">User Configuration</a>#}
{#                            <a href="/admin/auth/group/" class="dropdown-item">Permissions and Groups</a>#}
{#                        </div>#}
{#                    </li>#}
                    {# --------------------------------------------------------------------------------------------- #}

                    {# APPS #}
{#                    <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-pages" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                            <i class="bx bx-flag mr-2"></i>Apps#}
{#                            <div class="arrow-down"></div>#}
{#                        </a>#}
{#                        <div class="dropdown-menu" aria-labelledby="topnav-pages">#}
{##}
{#                            <a href="#" class="dropdown-item text-danger">Website Builder</a>#}
{#                        </div>#}
{#                    </li>#}
                    {# --------------------------------------------------------------------------------------------- #}

                </ul>
            </div>
        </nav>
    </div>
</div>